# Generated by Django 3.1.1 on 2020-09-11 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bucket.base')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('bucket.base',),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bucket.base')),
                ('task', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bucket.bucket')),
            ],
            bases=('bucket.base',),
        ),
    ]
